hms-dbmi/cistrome-explorer

- CHANGELOG.md
- src/TrackRowInfo.js
- src/TrackRowLink.js
- src/TrackRowLink.scss
- src/demo/App.js
- src/viewconfigs/horizontal-multivec-local.json
> Row metadata links

- rollup.demo.utils.js
- src/demo/App.js
- src/demo/App.scss
> Import bootstrap css

- src/TrackRowInfo.js
- src/demo/App.js
More information about metadata, i.e., the category of each row and the attribute name of each dimension, is shown in **TrackRowInfo** views.
> Show categories and the attribute name in each dimension

- src/TrackColSelectionInfo.js
- src/TrackColTools.js
- src/TrackWrapper.js
> Dynamic genome interval text positions

- src/demo/App.js
- src/utils/options.js
This fixes a bug with the new demo config which has two higlass views.
> Fix rowInfoAttributes bug

- .documentation.yml
- src/CistromeHGW.js
- src/TrackControl.js
- src/TrackWrapper.js
- src/demo/App.js
- src/utils/array.js
- src/utils/options.js
- src/utils/options.spec.js
The interactive sorting should work even when options are array.
> Add "rowSort" to the default option when options are array

- src/TrackRowHighlight.js
- src/utils/select-rows.js
Related to "graying out rows": https://github.com/hms-dbmi/cistrome-higlass-wrapper/issues/44#issuecomment-585914658
> Reverse highlighting rows with keyword search

- src/TrackRowInfoVisDendrogram.js
> Add gray rectangle and tooltip when dendrogram is hidden

- src/TrackRowInfoVisDendrogram.js
My previous commit broke the dendrogram resizing. This should fix it.
> Fix resize dendrogram bug

- src/TrackRowSearch.js
> Add keyboard shortcuts in search box

- src/Tooltip.js
- src/Tooltip.scss
- src/TrackRowInfoVisDendrogram.js
- src/TrackRowInfoVisLink.js
- src/TrackRowInfoVisNominalBar.js
- src/TrackRowInfoVisQuantitativeBar.js
- src/utils/array.js
- src/utils/color.js
> Add a tooltip generator to show color info

- src/TrackRowInfoVisQuantitativeBar.js
- src/demo/App.js
- src/utils/d3.js
> Add x-axis for quantitative bar charts

- CHANGELOG.md
- package.json
- src/TrackRowInfo.js
- src/TrackRowInfoControl.js
- src/TrackRowInfoVisDendrogram.js
- src/TrackRowInfoVisLink.js
- src/TrackRowInfoVisNominalBar.js
- src/TrackRowInfoVisQuantitativeBar.js
- src/TrackRowSearch.js
- src/TrackRowSearch.scss
Fixes #98.
I also updated the version from 0.1.0 to 0.2.0 and moved all of the changelog entries that we added after our 2/19 meeting under the new version. I think it may be a good way to separate the features that we work on between each monthly meeting.
> Search suggestion feature

- src/demo/App.js
> Add <select> element for demo choice

- src/TrackRowInfoVisNominalBar.js
> Show background color on nominal visualization hover

- CHANGELOG.md
- src/TrackRowInfoVisLink.js
- src/TrackRowInfoVisNominalBar.js
This adds a hover effect for links. Fixes #167
> Add hover link styles

- CHANGELOG.md
- rollup.demo.utils.js
- src/CistromeHGWConsumer.js
- src/TrackColTools.js
- src/utils/viewconf.js
- src/utils/viewconf.spec.js
- src/viewconfigs/horizontal-multivec-1.json
- src/viewconfigs/horizontal-multivec-2.json
- src/viewconfigs/horizontal-multivec-3.json
- src/viewconfigs/horizontal-multivec-4.json
- src/viewconfigs/horizontal-multivec-5.json
- src/viewconfigs/horizontal-multivec-6.json
- src/viewconfigs/horizontal-multivec-7.json
- src/viewconfigs/horizontal-multivec-8.json
Fixes #143 
Fixes #24 
Fixes #83 
Fixes #19 
Un-blocks #12 
Removes horizontal-stacked-bar tracks from our view config json files due to https://github.com/higlass/higlass-multivec/issues/34
> Upgrade to higlass 1.9.0

- src/viewconfigs/horizontal-multivec-1.json
- src/viewconfigs/horizontal-multivec-2.json
- src/viewconfigs/horizontal-multivec-3.json
- src/viewconfigs/horizontal-multivec-4.json
- src/viewconfigs/horizontal-multivec-5.json
- src/viewconfigs/horizontal-multivec-6.json
- src/viewconfigs/horizontal-multivec-7.json
- src/viewconfigs/horizontal-multivec-8.json
> Add searchbar options in all viewConfigs

- src/viewconfigs/horizontal-multivec-1.json
> Update the x domain of demo 1 to center on MYC

- src/utils/cistrome.js
> Catch fetch errors for data table

- src/CistromeHGWConsumer.scss
- src/DataTable.js
- src/DataTableForIntervalTFs.js
> Add close button in data table

- src/TrackRowInfoVisQuantitativeBar.js
> Add axis inside of each track

- CHANGELOG.md
- src/CistromeHGWConsumer.js
- src/TrackRowHighlight.js
- src/TrackRowInfo.js
- src/TrackWrapper.js
- src/ViewWrapper.js
- src/utils/d3.js
- src/utils/two.js
- src/utils/wrap-svg.js
> Include wrapper visualizations in svg exports

- README.md
> Add external resources

- CHANGELOG.md
- src/CistromeHGWConsumer.js
> SVG export bug fix

- package.json
- src/demo/CistromeExplorer.js
- src/demo/CistromeToolkit.js
- src/utils/cistrome.js
- yarn.lock
**TODO**
- CORS & credential issue (https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSNotSupportingCredentials)
- To get csrf token programmatically
> BED file API

- src/HiGlassMetaConsumer.js
- src/utils/contexts.js
> Properly reset context upon changing a demo

- src/demo/CistromeExplorer.js
> Allow loading the same bed file again

- src/demo/CistromeExplorer.js
> Support selecting a field to aggregate rows

- src/TrackRowInfoVisDendrogram.js
- src/TrackRowInfoVisNominalBar.js
- src/demo/DataTable.js
> Fix sorting table in Chrome

- src/demo/CistromeExplorer.js
- src/demo/CistromeExplorer.scss
- src/viewconfigs/horizontal-multivec-1.js
> Allow resizing the width of heatmap

- package.json
- rollup.demo.utils.js
- src/demo/CistromeExplorer.js
- src/viewconfigs/horizontal-multivec-1.js
- yarn.lock
> Add a GWAS track
