- src/TrackRowInfo.js
- src/TrackWrapper.js
- src/demo/App.js
- src/utils-options.js
Support the flexibility in selecting the varying number of attributes to show in TrackRowInfo.
- Before: 
```
{
...,
infoAttrPrimary, // string
infoAttrSecondary // string
}
```
- After:
```
{
...,
infoAttributes // array
}
```
Any feedback/modifications for better readability or style-consistency are welcome!
> Generalized TrackRowInfo options to accept a array of attributes

- src/TrackRowLink.js
- src/TrackWrapper.js
- src/demo/App.js
- src/utils-options.js
I added an option (**rowLinkNameAttribute**) to specify an attribute that is used to display the name of each URL, instead of the URL itself. This can enable the URL to be more readable within the limited space. 
When **rowLinkNameAttribute** is not specified, the original url (i.e., **rowLinkAttribute**) will be displayed by default.
> Added an option to specify the display name for url

- .documentation.yml
- src/CistromeHGW.js
- src/CistromeHGW.scss
- src/TrackColSelectionInfo.js
- src/TrackColSelectionInfo.scss
- src/TrackColTools.js
- src/TrackRowInfo.js
- src/TrackRowLink.js
- src/TrackWrapper.js
- src/constants.js
- src/utils-genome.js
- src/utils-viewconf.js
- src/utils-viewconf.spec.js
- src/viewconfigs/horizontal-multivec-1.json
- src/viewconfigs/horizontal-multivec-3.json
This adds the `TrackColSelectionInfo` component, which appears if a genomic selection has been made, and shows the genomic coordinates. If the interval is less than 2 Mb, a link to search for the interval on http://dbtoolkit.cistrome.org/ appears. Fixes #11.
Because higlass uses absolute genome coordinates, it seems that I need to fetch the chromosome sizes for the current genome assembly before doing the conversion. I will also try to check with the higlass developer slack and ask whether making this request is necessary or if there is some way to obtain this information directly from the higlass component if it already has the chromosome sizes. https://github.com/hms-dbmi/cistrome-higlass-wrapper/compare/keller-mark/genome-interval-info?expand=1#diff-696d2da7332664c34286d27e050ab540R15 …
> Show genome interval coordinates and dbtoolkit link

- src/TrackRowInfo.js
- src/VerticalBarTrack.js
- src/utils/two.js
This adds jsdoc comments, but also updates the (x,y) parameters for the `two.makeRect` function so they no longer need to be for the center of the rect. And I changed the `text.align` options to "start", "middle", "end" to be more consistent with the canvas and SVG APIs.
> More comments in the two.js file

- src/TrackRowInfo.js
- src/VerticalBarTrack.js
- src/demo/App.js
I added horizontal bars for both the left and right vertical tracks (Fixes #48).
Mouse events are now simply triggered when a mouse enters the whole rectangular area of each row.
> Implemented horizontal bars for quantitative values

- .documentation.yml
- src/CistromeHGWConsumer.js
- src/TrackRowInfo.js
- src/TrackRowInfoControl.js
- src/TrackRowInfoVisBar.js
- src/TrackRowInfoVisLink.js
- src/TrackRowSearch.js
- src/TrackWrapper.js
- src/utils/constants.js
- src/utils/select-rows.js
This pull request does some refactoring to remove the PubSub events for sorting and searching, and replaces them with onSortRows and onSearchRows functions that are passed down to the TrackRowInfoControl components.
> Remove sort and search pubsubs

- src/TrackResizer.scss
- src/TrackRowSearch.js
I repositioned text fields for keyword search not to overlap vertical tracks, which is caused by using 'vertical' arrangement for three buttons.
I also added css styles that make the resizer component bigger on mouse hover.
> Reposition text fields for keyword search

- src/TrackRowInfo.js
- src/TrackRowInfoVisBar.js
- src/TrackRowInfoVisLink.js
- src/demo/App.js
- src/utils/vis.js
I added textual descriptions about sorting status in the title of vertical tracks.
In the future, we can add icons for indicating the sorting (and filtering) status and even give some interactions on that components. However, I think we are fine with this textual description for now.
This fixes #66.
> Add description in title for sorting status

- src/TrackRowInfo.js
- src/TrackRowInfoVisBar.js
- src/TrackRowInfoVisLink.js
- src/TrackWrapper.js
- src/utils/vis.js
Added textual descriptions about the filtering status, just like the one for the sorting status.
This fixes #81
> Add indicator for filtered status

- .documentation.yml
- CHANGELOG.md
- src/CistromeHGWConsumer.js
- src/TrackRowInfo.js
- src/TrackRowInfoControl.scss
- src/TrackRowInfoVisDendrogram.js
- src/TrackRowInfoVisNominalBar.js
- src/TrackRowInfoVisQuantitativeBar.js
- src/demo/App.js
- src/demo/App.scss
- src/utils/d3.js
- src/utils/options.js
- src/utils/select-rows.js
- src/viewconfigs/horizontal-multivec-1.json
I implemented stacked bar charts, modifying a `fieldInfo` option to accept an array of multiple data fields for this purpose.
Sorting rows works based on the sum of multiple values.
Since we have not decided how to support filtering/highlighting for quantitative values, filtering and highlighting in this field are not supported yet.
To manage the `TrackRowInfoVisBar.js` file to be more simple, I separated it into two files: `TrackRowInfoVisQuantitativeBar.js` and `TrackRowInfoVisNominalBar.js.`
I changed the default demo as "Demo 1" because now we have filtering options and demo 1 data contains quantitative data.
Fixes #96.
> Add stacked bar chart for multiple quantitative fields

- src/CistromeHGWConsumer.scss
- src/TrackRowInfoVisQuantitativeBar.js
- src/utils/color.js
I added hidden canvas for mouse events. The offset issue was because the following line was missing:
`const ratio = getRetinaRatio(hiddenContext);`
This fixes #116.
> Add hidden canvas for mouse events in quantitative bar charts

- package.json
- src/CistromeHGWConsumer.js
- src/TrackRowInfo.js
- src/TrackRowInfoControl.js
- src/TrackRowInfoVisDendrogram.js
- src/TrackRowInfoVisLink.js
- src/TrackRowInfoVisNominalBar.js
- src/TrackRowInfoVisQuantitativeBar.js
- src/TrackWrapper.js
- src/utils/d3.js
- src/utils/options.js
- src/utils/select-rows.js
- yarn.lock
Implements filtering of the dendrogram by clicking near a node to select the subtree containing its descendants. Uses https://github.com/d3/d3-delaunay to locate the node closest to the mouse click.
Also, I renamed the `onFilter` function to `onFilterRows` to match the `onSortRows` and `onSearchRows` functions and just to be more explicit about what is being filtered.
Fixes #97
> Dendrogram filtering by clicking root node of subtree

- src/CistromeHGWConsumer.js
- src/TrackWrapper.js
- src/demo/App.js
This is a pull request into your pull request branch.
I was seeing this warning, so I think the `onMetadataLoad` should be called in a `useEffect` rather than directly in the render function.
https://github.com/hms-dbmi/cistrome-higlass-wrapper/compare/sehilyi/fix-78...keller-mark/fix-78-update?expand=1#diff-adae11a6acfedf9f91b7f703a7c80679R50
I also removed the processWrapperOptions call from the `useState()` call, since the wrapper options only need to be processed when the `optionsRaw` changes https://github.com/hms-dbmi/cistrome-higlass-wrapper/compare/sehilyi/fix-78...keller-mark/fix-78-update?expand=1#diff-1a84645fc8258869422733acd3c33673R180
https://github.com/hms-dbmi/cistrome-higlass-wrapper/compare/sehilyi/fix-78...keller-mark/fix-78-update?expand=1#diff-1a84645fc8258869422733acd …
> Minor changes to pull request 121

- .documentation.yml
- src/CistromeHGWConsumer.js
- src/TrackRowInfo.js
- src/TrackWrapper.js
- src/demo/App.js
- src/utils/options.js
- src/utils/options.spec.js
- src/utils/viewconf.js
- src/utils/viewconf.spec.js
I added [a callback function](https://github.com/hms-dbmi/cistrome-higlass-wrapper/blob/e4b9a80a0d4235f071e389841efe171d6074a24c/src/CistromeHGWConsumer.js#L61) to sort, filter, and highlight based on the initial wrapper options.
[Because rowInfo is loaded once a HiGlass is rendered](https://github.com/hms-dbmi/cistrome-higlass-wrapper/blob/e4b9a80a0d4235f071e389841efe171d6074a24c/src/TrackWrapper.js#L83), you can see that views are re-rendered at first for the initial sorting, filtering, and highlighting options. For this purpose, we may want to move this rowInfo part from `TrackWrapper.js` to `CistromeHGMConsumer.js`. What do you think about this?
I also cleaned up a little in the part of dealing with 'raw Options' and 'processed options'. Instead of updating `optionsRaw` and then …
> Support initial sorting, filtering, and highlighting options

- CHANGELOG.md
- src/CistromeHGWConsumer.js
- src/TrackRowInfoVisDendrogram.js
- src/TrackRowInfoVisLink.js
- src/TrackRowInfoVisNominalBar.js
- src/TrackRowInfoVisQuantitativeBar.js
- src/utils/two.js
- src/utils/vis.js
It looks FireFox and IE do not support `actualBoundingBoxAscent` and  `actualBoundingBoxDescent`, making titles or backgrounds not to be rendered (https://developer.mozilla.org/en-US/docs/Web/API/TextMetrics).
I changed the text height measurement for canvas:
https://github.com/hms-dbmi/cistrome-higlass-wrapper/blob/e1af89e050f0098f14e8d94ae771551c9ca3f6fb/src/utils/two.js#L603-L604
> Minor update on text height measurement

- src/TrackRowSearch.js
- src/TrackRowSearch.scss
- Added filter icons in front of each suggestion to explicitly show that clicking on a keyword directly filter rows.
- Changed styles a bit, mainly in order to more clearly show suggestions (gray -> black) and to show the matching keywords less visually salient (yellow bg -> bold font).
- Showed top N suggestions even if the size of potential results are larger than predefined N.
> Minor changes in keyword suggestions

- src/TrackColSelectionInfo.js
- src/TrackColTools.js
- src/TrackColTools.scss
- src/TrackWrapper.js
- src/demo/App.js
- src/demo/fakedata/index.js
- src/viewconfigs/horizontal-multivec-7.json
This pull request adds a third demo, where the horizontal-multivec track is a 'top' track rather than a 'center' track, and there is another track below it. I updated the css for the genome interval selection button so that the track below can still pan and zoom with the mouse.
Related to #144
> Add top track position demo

- src/TrackRowInfoControl.js
- src/TrackRowInfoControl.scss
- src/TrackRowInfoVisDendrogram.js
Alternatively uses a "sort_tree" icon on the middle for unsorted dendrograms, and clicking on the icon rearrange rows by dendrogram arrangements.
I think this is a bit easier for users to find a button to reorder rows in dendrograms.
I think we can close #87.
> Minor updates on dendrogram sorting buttons

- src/demo/App.js
- src/demo/fakedata/index.js
- src/viewconfigs/horizontal-multivec-8.json
This new demo has two horizontal-multivec tracks in the same higlass view, and each track is using different metadata.
Fixes #144
> Add demo config with center and top tracks

- .documentation.yml
- src/TrackRowInfo.js
- src/TrackRowInfoVis.js
- src/TrackRowInfoVisDendrogram.js
- src/TrackRowInfoVisLink.js
- src/TrackRowInfoVisNominalBar.js
- src/TrackRowInfoVisQuantitativeBar.js
- src/utils/d3.js
This pull request makes a new component, TrackRowInfoVis, which is a container for an individual visualization component and its resizer element. So now TrackRowInfo can be much simpler, and this allows us to show/hide the resizer component when the visualization component is hovered, which fixes #158 
It also changes the resizing logic to use d3-drag https://github.com/d3/d3-drag
> Only show width resizer on hover

- .documentation.yml
- src/DataTable.js
- src/DataTable.scss
- src/DataTableForIntervalTFs.js
- src/TrackColSelectionInfo.js
- src/TrackColTools.js
- src/TrackRowInfoControl.scss
- src/TrackWrapper.js
- src/utils/cistrome.js
- src/utils/constants.js
(This is a pull request into your pull request.)
The useEffect and useState after the return statement [here](https://github.com/hms-dbmi/cistrome-higlass-wrapper/compare/sehilyi/fix-137...keller-mark/table-refactoring?expand=1#diff-adae11a6acfedf9f91b7f703a7c80679L58) in TrackWrapper  were throwing this error so I moved them to a separate component to fix it
Also these changes should partially address the TODO statement about moving the logic out of the TrackWrapper (though obviously the positioning of the table eventually should be addressed)
This pull request replaces the `XMLHttpRequest` with `fetch` because I think the Promises that fetch uses are a bit easier to deal with than the callback parameters that XMLHttpRequest uses …
> Some refactoring of the datatable

- .documentation.yml
- CHANGELOG.md
- src/TrackRowInfo.js
- src/TrackRowInfoVis.js
- src/TrackRowInfoVisDendrogram.js
- src/TrackRowInfoVisLink.js
- src/TrackRowInfoVisNominalBar.js
- src/TrackRowInfoVisQuantitativeBar.js
- src/TrackWrapper.js
> Compute nominal bar color scale based on original rowInfo array to keep colors after filtering events

- src/utils/options.js
- src/utils/options.spec.js
`updateWrapperOptions` function was making the bug (filtering broken) after I updated the function for the previous pull request. There already were many tests for this function but was not covering a specific case. I added more tests and also tests for the `addTrackWrapperOptions` function. This function is quite straightforward, but I just wanted to make sure.
Fixes #185
> Fix bug on filtering and add tests

- CHANGELOG.md
- src/DataTable.js
This pull request adds the `onCheckRows` option for the DataTable component. If the function is provided as a prop, then the checkboxes will be rendered (but otherwise no checkboxes will be rendered).
Fixes #184
> Data table checkboxes

- src/utils/cistrome.js
Used `.catch` function to catch the rejected request. Would this fix? #171
> Catch unsecure request (http from https domain)

- src/utils/color.js
- src/utils/options.js
- src/utils/two.js
- src/utils/viewconf.js
This pull request fixes the first bug illustrated in #201. The bug was based on the `measureTextSvg()` where the `text.node().getBBox()` line does not catch errors but also not assign proper text dimensions, (`width` and `height` === 0). This caused titles to be improperly positioned only in Chrome in my local settings.
> Properly position titles of wrapper tracks in SVG

- src/viewconfigs/horizontal-multivec-1.json
- src/viewconfigs/horizontal-multivec-2.json
- src/viewconfigs/horizontal-multivec-3.json
- src/viewconfigs/horizontal-multivec-4.json
- src/viewconfigs/horizontal-multivec-5.json
- src/viewconfigs/horizontal-multivec-6.json
- src/viewconfigs/horizontal-multivec-7.json
- src/viewconfigs/horizontal-multivec-8.json
- src/viewconfigs/horizontal-multivec-9.json
- src/viewconfigs/meeting-2020-04-29.json
Removed two options, `view.layout.moved` and `view.layout.static`, in all the demo view configs since they are not allowed according to the definition of json schema in HiGlass and were making warning messages in console.
React-grid-layout autogenerates these options when rendering HiGlass (https://github.com/higlass/higlass/pull/700), and we perhaps took these options by copy and pasting the entire viewConfigs shown on the interface of HiGlass settings.
Before:
> Remove view.layout.moved/static in demo viewConfigs

- src/ViewWrapper.js
The system crashed upon the genomic interval selection when demo datasets do not have information about genomic coordinate systems (i.e., `multivecTrack.tilesetInfo.coordSystem` being `null`). As there is currently no use cases for using the horizontal bar without being able to select genomic intervals, I updated to prevent  from rendering the horizontal bar when `coordSystem` is missing.
(Fixes #231)
> Show genomic interval bar only when coordSystem presents

- CHANGELOG.md
- src/DataTable.js
- src/DataTable.scss
- src/DataTableForIntervalTFs.js
- src/TrackRowInfoControl.scss
- src/TrackRowInfoVisDendrogram.js
- src/TrackRowInfoVisQuantitativeBar.js
- src/ViewWrapper.js
- src/demo/App.js
- src/demo/App.scss
I've updated the appearance and formats of the API result table. 
I used custom css without any styling library (e.g., bootstrap) so we can easily change the appearance for example using the "drawer" layout you've mentioned. Here, I used the modal-like layout for showing the table because I thought that the table are currently too wide to use such the drawer layout.
- e.g., "OverlapPeakNumber" => "Overlap Peak Number"
- e.g., "DCid"
> API result table

- CHANGELOG.md
- package.json
- src/CistromeToolkit.scss
- src/TrackRowFilter.js
- src/TrackRowFilter.scss
- src/TrackRowInfoControl.js
Fix z-index between track resizers, filtering components, and a toolkit view: Resizers are placed under filtering components, and the filtering components are placed under the toolkit view.
I also renamed `TrackRowSearch` => `TrackRowFilter` for the clarity.
**Before:**
**After:**
> Fix z-index

- package.json
- rollup.demo.utils.js
I think I introduced a bug in the workerSetPix function in higlass, so this reverts to the previous version while I work on fixing that.
> Revert to higlass v1.10.1 due to workerSetPix bug

- .documentation.yml
- CHANGELOG.md
- src/HiGlassMetaConsumer.js
- src/utils/options.js
Fixes #294 
The problem was mainly based on my mistake from a previous PR, where I used a not-defined local variable, `condition`, in src/HiGlassMetaConsumer.js.
@keller-mark Should we add an es-lint configuration to avoid such bugs?
> Fix highlighting on dendrograms

- pipelines/cistrome-to-multivec/.gitignore
- pipelines/cistrome-to-multivec/README.md
- pipelines/cistrome-to-multivec/Snakefile
- pipelines/cistrome-to-multivec/cluster-profile.yml
- pipelines/cistrome-to-multivec/src/manifest_to_mv5.py
- pipelines/cistrome-to-multivec/src/utils.py
- pipelines/cistrome-to-multivec/submit.sh
Minor changes to the snakemake pipeline
- use snakemake "groups" to execute multiple related rules in the same cluster node to reduce overhead of submitting many separate slurm jobs
- add a bash script `submit.sh`
- update the partial list of files to process (but limit to 300 to prevent processing all files)
- add an s3 sync command to readme
- update the base resolution to 200
> Run pipeline

- CHANGELOG.md
- src/HiGlassMetaConsumer.js
- src/TrackRowInfoVisDendrogram.js
- src/TrackWrapper.js
- src/demo/demo.js
- src/utils/options.js
- src/utils/select-rows.js
- src/utils/select-rows.spec.js
Renamed `subtree` to `ancestors` in `HiGlassMeta` options for the clarity since the `subtree` options in filtering and sorting was finding nodes that have the identical 'ancestors'.
Fix #296
> Rename `subtree` to `ancestors`

- src/HiGlassMetaConsumer.js
- src/cistrome-api/bigwig.js
- src/demo/CistromeExplorer.js
- src/demo/CistromeToolkit.js
- src/demo/DataTable.js
- src/demo/DataTable.scss
- src/viewconfigs/horizontal-multivec-1.js
- src/viewconfigs/horizontal-multivec-atac.js
Using the Cistrome APIs like the following, one can add bigwig tracks to the visualization:
http://develop.cistrome.org/cistrome/samples/1/track?chrom=chr1&start_pos=100&end_pos=10000&bin_length=1000
> feat: allow adding a track from toolkit results using cistrome APIs
